inherit_gem:
  rubocop-salemove: config/default.yml

AllCops:
  Exclude:
    - bin/*

Metrics/MethodLength:
  CountComments: false
  Max: 35

Metrics/AbcSize:
  Max: 35

Metrics/ClassLength:
  Max: 170
